# Data Source Configuration
spring:
  datasource:
    url: jdbc:sqlite:./data/demo.db
    driver-class-name: org.sqlite.JDBC
  
# Hibernate Auto DDL Configuration
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
