# Data Source Configuration
spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  
# Hibernate Auto DDL Configuration
spring:
  jpa:
    hibernate:
      ddl-auto: update
